import type { CatalogSkill } from "@/lib/types";

export const skills: CatalogSkill[] = [
  {
    slug: "fridge-to-table-rescue", title: "Fridge-to-table rescue", category: "food-and-home",
    description: "Turn the food you already have into one feasible meal, using expiry urgency, time, equipment, and dietary constraints. Use when ingredients are mismatched, energy is low, or a generic recipe search would create more work.",
    outcome: "One feasible meal, substitutions, a parallel cooking order, and a leftover plan.",
    examples: ["What can I cook with half a cabbage, eggs, and rice?", "I have 25 minutes and only one pan.", "Use the spinach tonight before it goes bad."],
    tags: ["cooking", "ingredients", "leftovers", "meal", "low energy"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "weeknight-meal-logistics", title: "Weeknight meal logistics", category: "food-and-home",
    description: "Build a realistic weekly meal system around the calendar, dietary needs, preparation time, and ingredient reuse. Use when the difficulty is coordinating several dinners and one grocery trip—not inventing a single recipe.",
    outcome: "A calendar-aware meal plan, preparation schedule, and consolidated grocery list.",
    examples: ["Plan four dinners around two late work nights.", "Reuse ingredients without eating the same meal all week.", "Make a vegetarian plan for two adults and a picky child."],
    tags: ["meal planning", "groceries", "calendar", "family", "prep"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "household-reset-coordinator", title: "Household reset coordinator", category: "food-and-home",
    description: "Convert a messy home and a fixed time window into a prioritized reset. Use when the agent should separate sanitation and functional recovery from cosmetic tidying, then assign clear work across the people available.",
    outcome: "A focused 15-, 30-, or 60-minute reset with ownership and a stopping point.",
    examples: ["People arrive in 30 minutes and the house is chaos.", "Give two adults a 20-minute reset plan.", "I am exhausted; what matters most tonight?"],
    tags: ["cleaning", "chores", "home", "overwhelm", "household"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "home-maintenance-first-response", title: "Home maintenance first response", category: "food-and-home",
    description: "Help document a household problem, gather evidence, perform only low-risk checks, and choose between monitoring, further investigation, and professional help. Use for maintenance triage; immediately escalate gas, fire, electrical, structural, and active-water hazards.",
    outcome: "A safe first-response brief with evidence, permitted checks, and an escalation decision.",
    examples: ["There is a new stain spreading across the ceiling.", "My refrigerator is making a strange intermittent sound.", "Help me explain this issue to the landlord."],
    tags: ["maintenance", "repair", "landlord", "safety", "home"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "hosting-without-panic", title: "Hosting without panic", category: "food-and-home",
    description: "Backward-plan a small gathering around the guest list, dietary needs, space, budget, and available help. Use when preparation, cleaning, cooking, seating, arrival, and fallback options need to work as one calm plan.",
    outcome: "A backward timeline, menu and shopping plan, division of work, and fallbacks.",
    examples: ["Eight people are coming Saturday; where do I start?", "Plan a dinner for mixed dietary needs.", "I have one oven and two hours after work."],
    tags: ["hosting", "party", "dinner", "guests", "planning"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "weekly-life-reset", title: "Weekly life reset", category: "life-administration",
    description: "Run a bounded weekly review across calendar, home, food, money, relationships, and unfinished commitments. Use when someone needs a realistic next-week plan rather than a motivational speech or an unprioritized master list.",
    outcome: "A short review, resolved loose ends, and a capacity-aware plan for the next seven days.",
    examples: ["Help me reset for next week in 20 minutes.", "My calendar and chores are getting away from me.", "Turn these loose ends into a realistic week."],
    tags: ["weekly review", "planning", "calendar", "life admin", "reset"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "overwhelm-to-next-action", title: "Overwhelm to next action", category: "life-administration",
    description: "Turn a brain dump or overwhelming situation into one bounded problem, one immediate action, and a short recovery sequence. Use when generating a large to-do list would increase pressure. This is practical organization, not crisis or mental-health care.",
    outcome: "One stabilizing action, a tiny sequence, and an explicit not-now list.",
    examples: ["I feel overwhelmed and do not know where to begin.", "Everything feels urgent; pick the next action.", "Help me recover the rest of today without a giant list."],
    tags: ["overwhelmed", "next step", "brain dump", "priorities", "low energy"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "paperwork-decoder", title: "Paperwork decoder", category: "life-administration",
    description: "Translate a form, letter, or administrative notice into plain language, deadlines, required documents, open questions, and a completion checklist. Use for organization and comprehension; do not infer legal conclusions or invent missing policy details.",
    outcome: "A plain-language brief, document checklist, deadlines, and questions for the issuing body.",
    examples: ["What is this letter actually asking me to do?", "Turn this application into a checklist.", "Which documents am I missing before I submit?"],
    tags: ["paperwork", "form", "letter", "deadline", "documents"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "appointment-prep-brief", title: "Appointment prep brief", category: "life-administration",
    description: "Prepare a concise brief for a medical, financial, educational, or professional appointment. Use to organize purpose, chronology, documents, questions, and desired outcomes without diagnosing, interpreting professional rules, or replacing qualified advice.",
    outcome: "A one-page appointment brief with chronology, evidence, top questions, and desired outcome.",
    examples: ["Help me prepare for a doctor appointment.", "I need a clear brief for a school meeting.", "Organize my questions before I meet the accountant."],
    tags: ["appointment", "doctor", "meeting", "questions", "brief"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "moving-home-command-center", title: "Moving-home command center", category: "life-administration",
    description: "Create a dated moving plan that coordinates utilities, address changes, packing zones, essential items, vendors, handover, travel day, and first-night setup. Use when a move has a real date and several interdependent workstreams.",
    outcome: "A dated command plan, ownership map, essentials system, and moving-day fallback.",
    examples: ["We move in six weeks; build the plan.", "What should stay out of the moving boxes?", "Coordinate a move between two cities."],
    tags: ["moving", "packing", "utilities", "address change", "handover"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "bill-calendar-builder", title: "Bill calendar builder", category: "money-and-consumer",
    description: "Convert income dates, recurring bills, variable essentials, and due dates into a monthly payment calendar with cash-flow pressure points and reminders. Use for organization only; never recommend borrowing, investing, or moving money without the user's decision.",
    outcome: "A dated bill calendar, pressure-point warnings, and a reminder schedule.",
    examples: ["Map my bills against two monthly paydays.", "Which week is likely to be tight?", "Turn these due dates into reminders."],
    tags: ["bills", "budget", "calendar", "cash flow", "payments"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "subscription-cleanup", title: "Subscription cleanup", category: "money-and-consumer",
    description: "Run an evidence-based subscription audit using actual usage, renewal dates, cancellation routes, records, and post-cancellation verification. Use when someone wants to reduce recurring charges without relying on memory or impulsive keep-or-cancel judgments.",
    outcome: "A keep/cancel/review table, ordered cancellation plan, and verification checklist.",
    examples: ["Help me audit these recurring charges.", "Which subscriptions should I review first?", "Make sure I preserve proof after canceling."],
    tags: ["subscriptions", "cancel", "renewal", "recurring charges", "audit"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "major-purchase-decision", title: "Major purchase decision", category: "money-and-consumer",
    description: "Structure an expensive purchase around weighted needs, total cost of ownership, deal-breakers, research gaps, and reversibility. Use when feature comparison is obscuring the real decision. Do not recommend debt, investments, or unaffordable spending.",
    outcome: "A decision matrix, ownership-cost view, research gaps, and a clear decision rule.",
    examples: ["Help us choose between these two cars.", "Is the premium appliance worth it for our use?", "Build criteria before I compare laptops."],
    tags: ["purchase", "comparison", "decision", "total cost", "shopping"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "return-refund-escalation", title: "Return and refund escalation", category: "money-and-consumer",
    description: "Organize receipts, promises, policy text, and contact history into a calm, dated escalation sequence. Use for consumer communication after asking the country or region; avoid unsupported legal claims and preserve evidence at every step.",
    outcome: "An evidence file, escalation ladder, and concise messages with deadlines.",
    examples: ["The seller stopped replying about my refund.", "Draft a calm escalation using this receipt and chat history.", "What evidence should I preserve before I contact them again?"],
    tags: ["refund", "return", "consumer", "complaint", "escalation"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "scam-message-check", title: "Scam message check", category: "money-and-consumer",
    description: "Assess a suspicious email, text, listing, or request for impersonation, urgency, payment, credential, attachment, and link risks. Use to produce independent verification steps without clicking, replying, calling supplied numbers, or declaring certainty from limited evidence.",
    outcome: "A risk assessment, suspicious signals, safe verification route, and account-protection steps.",
    examples: ["Is this suspicious text from my bank real?", "A buyer wants me to pay a courier first.", "Check this urgent password-reset email without opening the link."],
    tags: ["scam", "phishing", "suspicious text", "fraud", "verification"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "boundary-setting-rehearsal", title: "Boundary-setting rehearsal", category: "relationships-and-care",
    description: "Define a specific interpersonal boundary, express it without over-explaining, rehearse likely pushback, and plan consistent follow-through. Use for ordinary relationship communication, not coercion, abuse intervention, or immediate safety situations requiring specialist help.",
    outcome: "A concise boundary script, pushback rehearsal, and follow-through plan.",
    examples: ["Help me say I cannot answer work messages at night.", "Rehearse how to decline repeated family requests.", "Make this boundary clear without sounding hostile."],
    tags: ["boundary", "communication", "rehearsal", "pushback", "relationships"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "apology-and-repair", title: "Apology and repair", category: "relationships-and-care",
    description: "Craft an accountable apology that names the action and impact, removes excuses, proposes proportionate repair, and identifies the behavior that must change afterward. Use when the goal is genuine accountability, not image management or pressured reconciliation.",
    outcome: "A direct apology, repair offer, and concrete change commitment.",
    examples: ["I missed an important commitment; help me apologize.", "Remove the excuses from this message.", "What repair should happen after I say sorry?"],
    tags: ["apology", "repair", "accountability", "conflict", "relationship"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "heated-message-cooldown", title: "Heated-message cooldown", category: "relationships-and-care",
    description: "Decide whether an emotionally charged message should be sent, delayed, shortened, or turned into a conversation. Use to preserve the underlying need while removing escalation, threats, mind-reading, and irreversible language.",
    outcome: "A send/delay/talk decision, a de-escalated draft, and a plan for the underlying issue.",
    examples: ["Should I send this angry text tonight?", "Keep my point but remove the escalation.", "Turn this long message into a request for a conversation."],
    tags: ["angry text", "message", "conflict", "cooldown", "communication"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "household-responsibility-agreement", title: "Household responsibility agreement", category: "relationships-and-care",
    description: "Turn recurring household conflict into explicit ownership, frequency, minimum standards, handoff rules, and a review date. Use to account for invisible planning and monitoring work as well as visible chores.",
    outcome: "A shared ownership agreement with standards, handoffs, exceptions, and a review date.",
    examples: ["We keep arguing about who notices the chores.", "Define what 'clean enough' means for both of us.", "Split ownership without making one person the manager."],
    tags: ["chores", "household", "mental load", "agreement", "shared responsibility"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "shared-care-coordinator", title: "Shared-care coordinator", category: "relationships-and-care",
    description: "Organize non-clinical support for a child, older relative, recovering person, or pet across schedules, supplies, responsibilities, open questions, and handoffs. Use for coordination only; never make medical decisions or override the person receiving care.",
    outcome: "A care coordination board, ownership map, handoff format, and question list for professionals.",
    examples: ["Coordinate visits and groceries for my recovering parent.", "Make a clear pet-care handoff for the weekend.", "Split school pickup and supplies across three adults."],
    tags: ["care", "family", "pet", "handoff", "coordination"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "minimum-viable-workout", title: "Minimum viable workout", category: "sustainable-health",
    description: "Adapt an existing workout to the time, energy, equipment, and setting available while preserving its main training intent. Use for healthy adults seeking a shorter session; stop for pain, concerning symptoms, injury, pregnancy-specific, or medical needs.",
    outcome: "A shortened session with preserved intent, clear substitutions, and a stopping rule.",
    examples: ["Turn my 60-minute workout into 20 minutes.", "I only have resistance bands today.", "Keep the main strength work but lower the volume."],
    tags: ["workout", "gym", "exercise", "short session", "equipment"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "return-to-exercise", title: "Return to exercise", category: "sustainable-health",
    description: "Create a conservative exercise restart after a lapse using current capacity, schedule, preferred activities, and confidence. Use only when the user is not seeking injury rehabilitation or medical clearance; prioritize gradual exposure and symptom-aware stopping rules.",
    outcome: "A conservative two-week restart with minimums, progression criteria, and stop conditions.",
    examples: ["I missed my workouts for two months; help me restart.", "Make week one intentionally easy.", "I used to run regularly but have lost the habit."],
    tags: ["exercise", "restart", "missed workouts", "fitness", "routine"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "sleep-wind-down-reset", title: "Sleep wind-down reset", category: "sustainable-health",
    description: "Identify evening friction and design a small, testable wind-down routine using timing, environment, and behavior changes. Use for routine design, not to diagnose or treat insomnia, breathing disorders, persistent fatigue, or other medical concerns.",
    outcome: "A seven-night wind-down experiment with cues, reduced friction, and a review measure.",
    examples: ["I keep scrolling long after I meant to sleep.", "Build a 20-minute wind-down I can actually keep.", "My evenings are unpredictable; design a flexible routine."],
    tags: ["sleep", "wind down", "bedtime", "routine", "phone"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "habit-recovery", title: "Habit recovery", category: "sustainable-health",
    description: "Diagnose why a routine broke, cut unnecessary scope, and create a low-friction restart that avoids shame, all-or-nothing thinking, and artificial streak pressure. Use for ordinary behavior change, not addiction or clinical treatment.",
    outcome: "A failure diagnosis, smaller restart protocol, recovery rule, and review date.",
    examples: ["I broke my routine and cannot get going again.", "Make this habit smaller without making it meaningless.", "Help me avoid quitting after one missed day."],
    tags: ["habit", "routine", "restart", "consistency", "streak"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "desk-day-movement-plan", title: "Desk-day movement plan", category: "sustainable-health",
    description: "Place short movement, posture-change, and eye-break opportunities around a real workday without disrupting meetings or presenting movement as treatment. Use for general comfort and routine; refer persistent pain, weakness, numbness, or concerning symptoms to a clinician.",
    outcome: "A meeting-aware movement plan with tiny cues, flexible alternatives, and a review check.",
    examples: ["Fit movement into a day of back-to-back meetings.", "I forget to look away from the screen.", "Give me quiet movement options for an office."],
    tags: ["desk", "movement", "eye break", "office", "meetings"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "decision-journal", title: "Decision journal", category: "decisions-learning-travel",
    description: "Record a consequential decision, alternatives, assumptions, reversibility, uncertainty, premortem, and review date. Use when someone wants to improve decision quality and later distinguish a sound process from lucky or unlucky outcomes.",
    outcome: "A timestamped decision record with assumptions, confidence, safeguards, and review trigger.",
    examples: ["Create a journal entry for this job decision.", "Run a premortem before I commit.", "Help me record what I believe now so hindsight cannot rewrite it."],
    tags: ["decision", "journal", "premortem", "uncertainty", "review"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "personal-project-rescue", title: "Personal project rescue", category: "decisions-learning-travel",
    description: "Recover a stalled personal project by reconstructing context, locating the actual blockage, cutting scope, and defining one finishable milestone. Use when the project still matters but momentum and working memory have decayed.",
    outcome: "A recovered context brief, blockage diagnosis, reduced scope, and next finishable milestone.",
    examples: ["I abandoned this project three months ago; help me restart.", "Cut this hobby project to something finishable.", "Figure out whether I am blocked by uncertainty or effort."],
    tags: ["project", "stuck", "restart", "scope", "milestone"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "learn-by-doing", title: "Learn by doing", category: "decisions-learning-travel",
    description: "Convert a learning goal into a short explanation, worked example, guided attempt, independent attempt, feedback loop, and retrieval schedule. Use when active practice is more valuable than another passive reading list.",
    outcome: "A practice sequence with a real attempt, feedback criteria, and spaced retrieval prompts.",
    examples: ["Teach me this by making me try it.", "Turn this topic into a 30-minute practice session.", "Do not give me the answer until I attempt it."],
    tags: ["learning", "practice", "study", "retrieval", "example"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "packing-by-scenario", title: "Packing by scenario", category: "decisions-learning-travel",
    description: "Build a packing system from the itinerary, weather, activities, local norms, luggage limits, laundry access, and consequences of forgetting an item. Use instead of a universal list; verify current weather and carrier rules when available.",
    outcome: "A scenario-based packing list, wear-in-transit plan, critical-item check, and final sweep.",
    examples: ["Pack for five days with one small carry-on.", "I need work, hiking, and one formal dinner.", "Prioritize what would be difficult to replace abroad."],
    tags: ["packing", "travel", "luggage", "weather", "checklist"], version: "1.0.0", updated: "2026-07-17",
  },
  {
    slug: "travel-day-contingency", title: "Travel-day contingency", category: "decisions-learning-travel",
    description: "Audit a specific travel day for transfer buffers, documents, connectivity, medications, payments, delays, lost luggage, and missed connections. Use to create an offline fallback brief; verify current operator and border information from authoritative sources.",
    outcome: "A risk-audited timeline and compact offline fallback brief for disruptions.",
    examples: ["Audit this itinerary for a tight connection.", "What should I save offline before the trip?", "Make a plan for delayed bags and a missed last train."],
    tags: ["travel day", "flight", "connection", "delay", "offline"], version: "1.0.0", updated: "2026-07-17",
  },
];

export function getCatalogSkill(slug: string) {
  return skills.find((skill) => skill.slug === slug);
}

export function getSkillsByCategory(category: string) {
  return skills.filter((skill) => skill.category === category);
}
