export type SkillSpec = {
  objective: string;
  intake: string[];
  workflow: Array<{ name: string; instruction: string }>;
  rules: string[];
  boundaries: string[];
  output: string[];
};

export const specs: Record<string, SkillSpec> = {
  "fridge-to-table-rescue": {
    objective: "Produce one realistic meal from what is already available while minimizing waste, delay, and cleanup.",
    intake: ["Available ingredients and approximate quantities", "Items that must be used soon", "Dietary restrictions and foods to avoid", "Time, energy, servings, and acceptable complexity", "Equipment, pantry staples, and leftover capacity"],
    workflow: [
      { name: "Inventory the useful core", instruction: "Group ingredients into protein, produce, starch, flavor, and finishing elements. Mark uncertain quantities instead of assuming them." },
      { name: "Prioritize urgency", instruction: "Identify ingredients most likely to spoil or lose quality. Prefer a plan that uses them without making the meal incoherent." },
      { name: "Choose one meal shape", instruction: "Select one format such as a bowl, stir-fry, soup, tray meal, pasta, or filled wrap. Recommend it before offering alternatives." },
      { name: "Close only essential gaps", instruction: "Use pantry substitutions first. Ask about or suggest buying an item only when it materially changes feasibility." },
      { name: "Sequence the cooking", instruction: "Order preparation by longest lead time and show what can happen in parallel. Include temperatures or doneness cues when relevant." },
      { name: "Plan the remainder", instruction: "State what will remain, how to store it safely, and the simplest next use. Avoid promising a storage duration when food-safety context is uncertain." },
    ],
    rules: ["Prefer the feasible meal over the most impressive meal.", "Do not assume an ingredient is safe because it is present; ask about spoilage signs when relevant.", "Treat substitutions as optional and label how they change the result.", "Keep active cooking steps proportional to the user's energy and time."],
    boundaries: ["Do not override allergy, food-safety, or medically prescribed dietary restrictions.", "Tell the user to discard food with concerning odor, mold, damaged packaging, or unsafe storage history.", "Do not invent exact food-safety limits when country guidance or storage conditions are unknown."],
    output: ["Recommended meal and why it fits", "Ingredient use and substitutions", "Parallel cooking timeline", "Doneness and safety checks", "Leftover and cleanup plan"],
  },
  "weeknight-meal-logistics": {
    objective: "Create a weeknight meal system that fits the actual calendar, reuses ingredients, and lowers daily decision load.",
    intake: ["People, servings, dietary constraints, and strong dislikes", "Nights to cover and the schedule on each night", "Cooking capacity, energy, equipment, and budget", "Ingredients already available or needing use", "Shopping access, leftovers preference, and prep window"],
    workflow: [
      { name: "Map the week", instruction: "Label each night by available time and energy. Place the easiest or prepped meal on the hardest night." },
      { name: "Choose anchor meals", instruction: "Select a small number of distinct meals that share flexible components. Avoid superficial variety that requires many single-use ingredients." },
      { name: "Assign intentional leftovers", instruction: "Decide where a cooked component becomes a later lunch or dinner. Check safe storage and reheating requirements." },
      { name: "Schedule preparation", instruction: "Move washing, chopping, thawing, marinating, or batch cooking to the earliest sensible window. Do not create an exhausting prep day." },
      { name: "Consolidate shopping", instruction: "Combine duplicates, subtract known pantry stock, and group the list by store section. Mark quantities that require confirmation." },
      { name: "Add a failure meal", instruction: "Include one shelf-stable, frozen, or minimal-effort fallback that respects dietary needs and budget." },
    ],
    rules: ["Plan to the busiest night, not the ideal week.", "Reuse ingredients while varying texture or format.", "Do not assign leftovers unless the user accepts them.", "Keep at least one meal flexible when the calendar is uncertain."],
    boundaries: ["Do not design around allergens or medical diets without explicit user constraints.", "Do not present nutrition estimates as medical advice.", "Flag safe cooling, storage, and reheating considerations without inventing local guidance."],
    output: ["Night-by-night plan", "Preparation schedule", "Ingredient reuse map", "Consolidated grocery list", "Fallback and leftover plan"],
  },
  "household-reset-coordinator": {
    objective: "Restore sanitation and function within a fixed time without turning the reset into an unlimited cleaning project.",
    intake: ["Time available and energy level", "Rooms or visible problems", "People available and any access limitations", "Immediate guests, children, pets, or safety concerns", "Essential outcome at the end of the reset"],
    workflow: [
      { name: "Stop active damage", instruction: "Handle spills, food left out, trip hazards, blocked exits, and other time-sensitive risks before ordinary tidying." },
      { name: "Define the finish line", instruction: "Translate the user's goal into two or three observable conditions. Explicitly name what will remain undone." },
      { name: "Clear function zones", instruction: "Recover the sink, toilet, walking paths, seating, or sleep surface that matters most for the next few hours." },
      { name: "Assign independent lanes", instruction: "Give each person a complete zone or function. Avoid making one person repeatedly coordinate or approve the others." },
      { name: "Run a timed pass", instruction: "Use a short work block followed by a two-minute scan. Stop or extend only with the user's remaining capacity." },
      { name: "Close the reset", instruction: "Remove rubbish, return tools, and choose at most one follow-up task for later. Preserve the visible win." },
    ],
    rules: ["Sanitation and safety outrank appearance.", "Contain unsorted items when sorting would consume the whole window.", "Match assignments to mobility, age, and access constraints.", "Never hide urgent maintenance problems to make a room look finished."],
    boundaries: ["Escalate sharps, bodily fluids, pests, mold, chemicals, fire, electrical, gas, and structural hazards to appropriate safe handling.", "Do not direct children to handle hazardous waste or chemicals.", "Do not shame the user or infer character from the condition of a home."],
    output: ["Finish line", "Timed priority sequence", "Ownership by person or zone", "Do-not-do list", "Closing check and one later task"],
  },
  "home-maintenance-first-response": {
    objective: "Create a safe, evidence-based first response to a household problem and choose the appropriate escalation level.",
    intake: ["What changed, where, and when it began", "Whether the issue is active, intermittent, or worsening", "Photos, sounds, smells, error codes, or visible damage", "Home type, tenancy status, and affected systems", "Any gas, smoke, heat, sparks, water, structural movement, or health symptoms"],
    workflow: [
      { name: "Screen for immediate danger", instruction: "Check first for gas odor, smoke, fire, sparking, shock risk, rapid water ingress, structural movement, or unsafe air. Stop ordinary troubleshooting when any is present." },
      { name: "Describe observations", instruction: "Separate what the user directly observed from explanations they suspect. Record time, location, frequency, and change." },
      { name: "Limit the affected area", instruction: "Suggest only low-risk containment that does not expose the user to electricity, gas, height, pressure, chemicals, or hidden damage." },
      { name: "Collect useful evidence", instruction: "Request photographs, short recordings, meter readings, model numbers, or neighboring observations only when safe and relevant." },
      { name: "Choose the response tier", instruction: "Classify as emergency action, urgent professional contact, routine service, landlord notification, or monitored observation. Explain the trigger for that tier." },
      { name: "Prepare the handoff", instruction: "Create a concise issue report with observations, timeline, actions already taken, access details, and questions." },
    ],
    rules: ["Treat uncertainty as a reason to reduce exposure, not to attempt more invasive checks.", "Never instruct work inside electrical panels, gas systems, roofs, pressurized systems, or structural assemblies.", "Use manufacturer or local authority instructions when available.", "Set a concrete monitoring trigger and time, not 'keep an eye on it.'"],
    boundaries: ["For gas, fire, carbon monoxide, electrical arcing, major flooding, or structural danger, tell the user to leave the area and contact local emergency or utility services.", "Do not claim to diagnose a fault remotely.", "Ask the country or locality before giving code, tenancy, or emergency-number guidance."],
    output: ["Risk tier and immediate action", "Observed facts and unknowns", "Safe checks or containment only", "Evidence checklist", "Professional or landlord handoff brief"],
  },
  "hosting-without-panic": {
    objective: "Build a calm hosting plan backward from guest arrival while protecting the host's time, budget, and attention.",
    intake: ["Date, arrival time, duration, and guest count", "Dietary needs, accessibility, children, and pets", "Space, seating, equipment, and available help", "Budget, menu ambition, and shopping access", "Host's available preparation windows and biggest worry"],
    workflow: [
      { name: "Define enough", instruction: "Set the minimum successful experience for food, comfort, and connection. Remove tasks that serve appearance but not guests." },
      { name: "Choose a resilient menu", instruction: "Favor dishes that tolerate holding, advance preparation, and dietary adaptation. Limit last-minute cooking bottlenecks." },
      { name: "Map constraints", instruction: "Check seats, serving ware, refrigeration, oven and burner use, coats, bathroom access, and arrival flow." },
      { name: "Plan backward", instruction: "Schedule shopping, cleaning, preparation, cooking, dressing, and a protected buffer from guest arrival backward." },
      { name: "Assign complete ownership", instruction: "Give helpers outcomes such as drinks or dessert rather than scattered micro-tasks. Confirm handoff times." },
      { name: "Prepare graceful fallbacks", instruction: "Choose what can be bought, skipped, served differently, or delayed when time or equipment fails." },
    ],
    rules: ["Protect a buffer before arrival.", "Do not let every dish require the same appliance at the same time.", "Confirm dietary restrictions rather than guessing severity.", "Prioritize guest comfort and host presence over decorative completeness."],
    boundaries: ["Treat disclosed allergies as safety constraints, not preferences.", "Do not recommend unsafe food holding or cross-contact practices.", "Account for accessibility without making assumptions about a guest's needs."],
    output: ["Definition of a successful gathering", "Backward timeline", "Menu and shopping list", "Space and ownership plan", "Fallbacks and final arrival check"],
  },
  "weekly-life-reset": {
    objective: "Review the essential domains of life and produce a realistic seven-day plan within current capacity.",
    intake: ["Available review time and current energy", "Calendar for the next ten days", "Unfinished commitments and messages", "Food, household, money, and relationship concerns", "Known deadlines, travel, care duties, and recovery needs"],
    workflow: [
      { name: "Capture open loops", instruction: "Collect loose commitments without solving them yet. Use existing notes, messages, and calendar entries rather than memory alone." },
      { name: "Scan fixed reality", instruction: "Mark appointments, deadlines, travel, care duties, and protected recovery. Estimate transition time." },
      { name: "Review essential domains", instruction: "Check food, home, money, people, health routines, and administration for only the next likely failure point." },
      { name: "Close tiny loops", instruction: "Complete items that take under two minutes only when doing so will not derail the review." },
      { name: "Allocate capacity", instruction: "Choose a small number of outcomes that fit the open blocks. Leave buffer instead of filling every gap." },
      { name: "Set the weekly bridge", instruction: "Place reminders, preparation steps, and a next review time where they will be encountered." },
    ],
    rules: ["Treat rest and transition as capacity costs.", "Choose outcomes before tasks.", "Move or renegotiate commitments that do not fit rather than silently overbooking.", "Keep a not-this-week list to preserve ideas without scheduling them."],
    boundaries: ["Do not treat severe distress or crisis as a productivity problem.", "Do not make financial, medical, or legal decisions during the review.", "Preserve the user's commitments and priorities; do not optimize their life around the agent's preferences."],
    output: ["Fixed commitments and constraints", "Three to five weekly outcomes", "Preparation and reminder actions", "Explicit not-this-week list", "Buffer and next review time"],
  },
  "overwhelm-to-next-action": {
    objective: "Reduce immediate cognitive load and identify one safe, meaningful next action without producing a new burden.",
    intake: ["The user's unedited brain dump", "Anything with a real deadline or immediate consequence", "Current location, time, and usable energy", "People waiting on the user", "Basic needs or safety issues requiring attention"],
    workflow: [
      { name: "Stabilize the moment", instruction: "Check whether the user needs water, food, medication they already take, a safe place, or urgent human support before organizing tasks." },
      { name: "Name the pressure", instruction: "Reflect the situation in one neutral sentence. Separate actual urgency from volume, ambiguity, and emotion." },
      { name: "Select one bounded problem", instruction: "Choose the item with the nearest meaningful consequence or greatest relief-to-effort ratio. Explain the choice briefly." },
      { name: "Shrink the first action", instruction: "Define a physical or communicative action that can begin within five minutes and does not depend on resolving the whole problem." },
      { name: "Create a short bridge", instruction: "Add no more than two actions that naturally follow. Stop before creating a comprehensive plan." },
      { name: "Park the remainder", instruction: "Preserve everything else in a not-now list with one review time. Do not force prioritization while capacity is low." },
    ],
    rules: ["One action must appear before any optional plan.", "Do not use urgency language unless a consequence is concrete.", "Prefer sending a renegotiation message over silently missing a commitment.", "If the user cannot act, reduce the action again or switch to stabilization."],
    boundaries: ["If the user indicates self-harm, danger, abuse, or inability to stay safe, prioritize immediate local human or emergency support.", "Do not diagnose anxiety, depression, ADHD, burnout, or other conditions.", "Do not frame rest, food, or care needs as failures of discipline."],
    output: ["Neutral situation summary", "One action to do now", "Two-step recovery bridge at most", "Not-now list", "Review time or person to contact"],
  },
  "paperwork-decoder": {
    objective: "Turn administrative text into an accurate action brief without inventing meaning or legal conclusions.",
    intake: ["Complete text or clear images of the document", "Issuer, recipient, and date received", "Country or jurisdiction when relevant", "Referenced enclosures, links, or prior correspondence", "The user's goal and any approaching deadline"],
    workflow: [
      { name: "Identify the document", instruction: "Record who issued it, who it addresses, its date, subject, and stated purpose. Flag missing pages or unreadable text." },
      { name: "Extract exact obligations", instruction: "List requested actions, required evidence, submission method, and stated deadlines. Preserve exact labels and reference numbers." },
      { name: "Translate carefully", instruction: "Explain dense language in plain terms while distinguishing direct text from interpretation. Quote only short phrases needed for accuracy." },
      { name: "Find dependencies", instruction: "Map which documents, signatures, payments, appointments, or answers must exist before another step can happen." },
      { name: "Surface uncertainty", instruction: "List ambiguous terms, conflicting dates, missing attachments, and questions that require the issuer or a qualified professional." },
      { name: "Build the completion pass", instruction: "Create an ordered checklist with evidence preservation, submission confirmation, and follow-up date." },
    ],
    rules: ["Never infer a deadline that is not stated.", "Keep names, identifiers, and document labels exact.", "Ask for missing pages before drawing conclusions from an incomplete notice.", "Separate 'the document says' from 'this may mean.'"],
    boundaries: ["Do not give legal advice or predict an authority's decision.", "Recommend qualified help when rights, penalties, immigration status, court action, or substantial money are at stake.", "Warn the user to redact unnecessary sensitive identifiers before sharing documents."],
    output: ["Document identity and purpose", "Plain-language summary", "Actions, documents, and deadlines", "Unknowns and questions", "Submission and follow-up checklist"],
  },
  "appointment-prep-brief": {
    objective: "Prepare a compact, factual brief that helps the user use limited appointment time well.",
    intake: ["Appointment type, date, duration, and professional", "Primary purpose and desired outcome", "Relevant chronology and prior actions", "Documents, records, measurements, or correspondence", "Questions, concerns, access needs, and anyone attending"],
    workflow: [
      { name: "Define the appointment job", instruction: "State what the user needs to understand, decide, request, or leave with. Limit the brief to this purpose." },
      { name: "Build a factual chronology", instruction: "Order relevant events by date and separate observations from interpretations. Include only details that affect the appointment." },
      { name: "Select evidence", instruction: "List documents and records to bring, where they are stored, and any missing items to request beforehand." },
      { name: "Rank questions", instruction: "Put the three questions with the greatest consequence first. Rewrite broad questions into specific requests for explanation or next steps." },
      { name: "Plan participation", instruction: "Note language, sensory, mobility, memory, privacy, or support-person needs and how to request them." },
      { name: "Prepare the close", instruction: "Add a check for decisions, responsibilities, deadlines, written instructions, and follow-up before leaving." },
    ],
    rules: ["Keep the main brief readable in one minute.", "Use the user's own observations and dates.", "Do not bury the desired outcome beneath background detail.", "Leave space for notes and answers."],
    boundaries: ["Do not diagnose, prescribe, interpret law, or make regulated financial decisions.", "For medical appointments, distinguish urgent symptoms from routine preparation and direct emergencies to local emergency care.", "Preserve privacy and include only necessary personal information."],
    output: ["Purpose and desired outcome", "Concise chronology", "Documents and evidence", "Top questions", "Close-of-appointment checklist"],
  },
  "moving-home-command-center": {
    objective: "Coordinate the dependencies of a home move around a fixed date and protect access to essential items.",
    intake: ["Origin, destination, move date, and key handover dates", "Household members, pets, accessibility, and travel method", "Home sizes, major items, and packing progress", "Vendors, vehicles, building rules, and budget", "Utilities, address obligations, and first-night needs"],
    workflow: [
      { name: "Build the date spine", instruction: "Place lease, completion, access, travel, vendor, and utility dates on one timeline. Flag gaps and impossible overlaps." },
      { name: "Create workstreams", instruction: "Separate packing, property handover, transport, administration, utilities, people and pet care, and destination setup." },
      { name: "Sequence dependencies", instruction: "Identify what must be booked, measured, approved, or completed before another action can start." },
      { name: "Pack by zone and access", instruction: "Assign labels, destination rooms, and a do-not-pack zone. Keep documents, medications, chargers, keys, clothing, and basic food personally accessible." },
      { name: "Design moving day", instruction: "Specify who has keys, directs movers, documents condition, manages dependents, and travels with essentials." },
      { name: "Prepare first night and fallback", instruction: "Plan sleep, hygiene, food, lighting, connectivity, and what happens if access or transport is delayed." },
    ],
    rules: ["Use dates and owners, not vague periods.", "Keep irreplaceable items out of unaccompanied freight.", "Photograph condition and readings when appropriate.", "Do not cancel essential services before replacement timing is confirmed."],
    boundaries: ["Ask for country or locality before stating address, tenancy, utility, or tax requirements.", "Do not move hazardous materials contrary to carrier or local rules.", "Refer contracts, disputes, and legal deadlines to qualified local guidance."],
    output: ["Dated command timeline", "Workstreams with owners", "Packing and essentials system", "Moving-day roles", "First-night and delay fallback"],
  },
  "bill-calendar-builder": {
    objective: "Make recurring payment timing visible and identify cash-flow pressure without giving financial advice.",
    intake: ["Country and preferred currency", "Income dates and conservative take-home amounts", "Recurring bill names, amounts, due dates, and payment methods", "Variable essentials and known irregular expenses", "Current reminders, autopay choices, and minimum cash buffer"],
    workflow: [
      { name: "Normalize the inputs", instruction: "Separate confirmed amounts from estimates and one-off expenses. Preserve due dates exactly." },
      { name: "Build the calendar", instruction: "Place income, bills, and essential spending windows in date order for a typical month." },
      { name: "Calculate running pressure", instruction: "Show a conservative running balance or coverage view only from user-provided figures. Mark uncertainty prominently." },
      { name: "Identify tight windows", instruction: "Flag clusters where obligations precede income or leave less than the user's chosen buffer." },
      { name: "Design reminders", instruction: "Set review and payment reminders early enough for the user's payment method. Distinguish reminder from automatic authorization." },
      { name: "Prepare exceptions", instruction: "List variable, quarterly, annual, or date-shifting charges that need a separate review." },
    ],
    rules: ["Never silently move a due date or amount.", "Do not count uncertain income as guaranteed.", "Show arithmetic so the user can verify it.", "Ask before treating autopay as preferred."],
    boundaries: ["Do not recommend borrowing, investing, debt prioritization, or moving funds between accounts.", "Do not initiate payments or request account credentials.", "Suggest a qualified local adviser or creditor contact when the user faces serious arrears or insolvency."],
    output: ["Inputs and assumptions", "Date-ordered monthly calendar", "Pressure points", "Reminder schedule", "Exceptions and user decisions"],
  },
  "subscription-cleanup": {
    objective: "Audit recurring services using evidence, then cancel or review them with a verifiable record.",
    intake: ["Recent recurring charges and known subscriptions", "Price, billing frequency, and next renewal", "Actual use and household users", "Cancellation route, contract term, and country", "Data, benefits, or files that could be lost"],
    workflow: [
      { name: "Build the inventory", instruction: "Match statements, app-store records, email receipts, and remembered services. Mark unidentified charges for independent verification." },
      { name: "Measure real use", instruction: "Record last use, frequency, unique value, substitutes, and who else depends on the service." },
      { name: "Expose timing and cost", instruction: "Normalize annual cost and surface trials, price changes, and upcoming renewals without inventing terms." },
      { name: "Classify deliberately", instruction: "Assign keep, cancel, downgrade, consolidate, or investigate with one evidence-based reason." },
      { name: "Sequence cancellations", instruction: "Prioritize near renewals and high-cost low-use services. Preserve data, benefits, receipts, and screenshots before cancellation." },
      { name: "Verify the result", instruction: "Record confirmation, effective end date, remaining access, refund statement, and a statement-check date." },
    ],
    rules: ["Actual use outranks intention to use.", "Do not count a retention offer as savings unless the new term is understood.", "Do not cancel a shared or safety-related service without confirming dependencies.", "Use independent account access, not links in suspicious messages."],
    boundaries: ["Ask for country before making claims about cooling-off periods, renewals, or cancellation rights.", "Do not request passwords, full card numbers, or security codes.", "Do not claim a charge is fraudulent; route unexplained charges through safe verification."],
    output: ["Subscription inventory", "Keep/cancel/review decisions", "Ordered action plan", "Evidence to preserve", "Post-cancellation verification dates"],
  },
  "major-purchase-decision": {
    objective: "Help the user make an expensive purchase from real needs, lifetime cost, and reversibility rather than marketing features.",
    intake: ["Purchase category, country, deadline, and budget ceiling", "Jobs the purchase must perform", "Usage frequency, environment, and expected ownership period", "Candidates already considered and available evidence", "Deal-breakers, financing constraints, resale, repair, and return options"],
    workflow: [
      { name: "Define the decision", instruction: "State whether the choice is buy, wait, repair, rent, used, or among candidates. Preserve the option to do nothing." },
      { name: "Translate needs into criteria", instruction: "Create a small set of weighted, observable criteria from actual use. Separate requirements from preferences." },
      { name: "Estimate ownership cost", instruction: "Include purchase, delivery, setup, consumables, energy, maintenance, insurance, accessories, repair, and likely resale when relevant." },
      { name: "Compare evidence", instruction: "Score only supported facts, mark unknowns, and distinguish manufacturer claims from independent evidence." },
      { name: "Run a premortem", instruction: "Ask how the choice could disappoint after six months and identify safeguards, trial routes, and return conditions." },
      { name: "Apply a decision rule", instruction: "Recommend one path when evidence supports it, or state the exact research needed to decide. Include a stop-shopping threshold." },
    ],
    rules: ["A deal-breaker overrides a high total score.", "Do not reward features the user will not use.", "Treat uncertain future use conservatively.", "Prefer reversible trials when candidates are close."],
    boundaries: ["Do not recommend debt, credit products, or spending beyond the user's stated ceiling.", "Verify current price, warranty, return, and safety information from authoritative sources when available.", "Ask for country before stating consumer rights or tax treatment."],
    output: ["Decision and requirements", "Weighted comparison", "Total ownership cost", "Unknowns and premortem", "Recommendation or research rule"],
  },
  "return-refund-escalation": {
    objective: "Build a factual, calm escalation that preserves evidence and asks for a specific consumer remedy.",
    intake: ["Country or region and purchase channel", "Product or service, amount, purchase date, and payment method", "Receipt, policy text, listing, and promises made", "Problem timeline and prior contact", "Requested resolution and any stated deadline"],
    workflow: [
      { name: "Assemble the record", instruction: "Create a dated evidence list and preserve originals, screenshots, order identifiers, delivery records, and prior messages." },
      { name: "State the discrepancy", instruction: "Compare what was promised, delivered, charged, or stated in policy using neutral, verifiable language." },
      { name: "Choose the first unresolved level", instruction: "Continue from the lowest channel that has not had a fair opportunity to respond. Avoid restarting the story at every contact." },
      { name: "Write the request", instruction: "Ask for one specific remedy, give the necessary evidence, and request a response by a reasonable date without invented legal threats." },
      { name: "Escalate by record", instruction: "Move to a supervisor, formal complaints route, marketplace, payment provider, or local consumer body only when appropriate to the country and evidence." },
      { name: "Close and verify", instruction: "Record the outcome, refund destination, promised date, return tracking, and follow-up if the remedy does not arrive." },
    ],
    rules: ["Facts, dates, and requested remedy come before emotion.", "Use the merchant's own policy language accurately.", "Do not threaten publicity, regulators, or chargeback as a bluff.", "Preserve deadlines and proof before returning an item."],
    boundaries: ["Do not make unsupported legal claims or guarantee a refund.", "Ask for country before naming statutory rights, agencies, limitation periods, or payment-dispute rules.", "Recommend qualified help for court action, large losses, fraud, or complex contracts."],
    output: ["Evidence index", "Factual timeline", "Escalation ladder", "Ready-to-send message", "Outcome and verification log"],
  },
  "scam-message-check": {
    objective: "Assess suspicious communications without interacting with attacker-controlled links or contact details.",
    intake: ["Exact message text with personal data redacted", "Claimed sender and communication channel", "What the message asks the user to do", "Whether the user clicked, replied, paid, downloaded, or shared information", "Country and relevant real relationship or account"],
    workflow: [
      { name: "Freeze interaction", instruction: "Tell the user not to click, reply, call supplied numbers, download attachments, pay, or share codes while checking." },
      { name: "Extract the claim", instruction: "Identify who the sender claims to be, the alleged event, requested action, deadline, and payment or credential route." },
      { name: "Inspect risk signals", instruction: "Check impersonation, urgency, secrecy, unusual payment, mismatched domains, shortened links, attachments, remote access, and verification-code requests." },
      { name: "Verify independently", instruction: "Use a known app, typed official website, statement, card, or independently sourced number. Do not use contact details from the suspicious message." },
      { name: "Assess exposure", instruction: "If the user interacted, identify exactly what was exposed and prioritize account, device, payment, and identity protection through official channels." },
      { name: "Document and report", instruction: "Preserve the message and headers where safe, block the sender, and use the relevant platform or local reporting route." },
    ],
    rules: ["Never declare safety from branding or sender name alone.", "Treat verification-code, gift-card, crypto, wire, and remote-access requests as high risk.", "Do not open or reproduce a suspicious link.", "State confidence and unknowns rather than claiming certainty."],
    boundaries: ["For active financial loss or account takeover, direct the user to the institution through a verified channel immediately.", "For threats, extortion, or immediate danger, prioritize local law enforcement or emergency support as appropriate.", "Do not perform malware analysis or ask the user to execute unknown files."],
    output: ["Risk level and confidence", "Claim and suspicious signals", "Safe independent verification steps", "Exposure response if needed", "Preservation and reporting checklist"],
  },
  "boundary-setting-rehearsal": {
    objective: "Define and rehearse a specific boundary that the user can communicate and consistently uphold.",
    intake: ["Relationship and recurring situation", "Behavior the user wants to limit or change", "What remains acceptable", "Likely pushback and practical dependencies", "Safety, power imbalance, and preferred communication channel"],
    workflow: [
      { name: "Define the boundary", instruction: "Write the user's own action or limit, not a rule intended to control another person. Make the triggering situation observable." },
      { name: "Choose the minimum explanation", instruction: "Give enough context to be clear without building a case for permission. Remove accusations, diagnoses, and debate invitations." },
      { name: "State the follow-through", instruction: "Name what the user will do if the situation recurs. Ensure it is safe, proportionate, and within the user's control." },
      { name: "Rehearse predictable responses", instruction: "Practice replies to guilt, bargaining, anger, minimization, repeated questions, and apparent agreement without change." },
      { name: "Plan delivery", instruction: "Choose timing, medium, privacy, and support that improve safety and clarity. Avoid delivering during peak conflict when possible." },
      { name: "Review consistency", instruction: "Set a point to assess whether the boundary is clear, workable, and being followed by the user." },
    ],
    rules: ["A boundary describes what the user will do.", "Do not over-explain after the limit has been understood.", "Use a broken-record response when repeated argument is the main pressure.", "Adjust the boundary if the user cannot safely or realistically follow through."],
    boundaries: ["Do not use ordinary communication rehearsal for coercive control, stalking, abuse, or immediate danger.", "Prioritize a trusted person, specialist service, or local emergency help when safety is uncertain.", "Do not pressure disclosure, confrontation, reconciliation, or continued contact."],
    output: ["Boundary definition", "Short primary script", "Follow-through action", "Pushback rehearsal", "Delivery and review plan"],
  },
  "apology-and-repair": {
    objective: "Create an accountable apology and a repair plan that changes what happens after the words are sent.",
    intake: ["What the user did or failed to do", "Known impact on the other person", "What responsibility the user accepts", "Any explanation that must be separated from excuse", "Possible repair and future prevention"],
    workflow: [
      { name: "Name the action", instruction: "Describe the specific behavior without euphemism, passive voice, or a conditional 'if.'" },
      { name: "Acknowledge impact", instruction: "Reflect the impact that is known and avoid claiming to know every feeling. Do not center the apologizer's discomfort." },
      { name: "Remove defenses", instruction: "Cut blame shifting, intention-as-exoneration, forced forgiveness, and language asking the harmed person to comfort the apologizer." },
      { name: "Offer proportionate repair", instruction: "Propose a concrete action that addresses the impact. Ask what would help when the right repair is not obvious." },
      { name: "Commit to change", instruction: "Name the system, behavior, or decision that will reduce recurrence and when it begins." },
      { name: "Respect the response", instruction: "Prepare for no reply, anger, refusal, or a request for space. Do not treat the apology as a claim on reconciliation." },
    ],
    rules: ["Use 'I am sorry that I…' rather than 'I am sorry you felt…'.", "Keep explanation shorter than accountability.", "Do not promise a change the user has no plan to make.", "Repair follows the affected person's needs, not the apologizer's preferred gesture."],
    boundaries: ["Do not craft manipulative apologies to evade consequences or regain access to someone.", "Do not encourage contact when the other person requested no contact.", "For abuse, serious harm, or legal exposure, recommend appropriate specialist support rather than optimizing a message."],
    output: ["Accountability statement", "Impact acknowledgment", "Repair offer", "Change commitment", "Response and space plan"],
  },
  "heated-message-cooldown": {
    objective: "Protect the user's underlying need while preventing an emotionally charged message from causing avoidable escalation.",
    intake: ["Unedited draft and intended recipient", "Event that triggered the message", "What the user wants to happen next", "Urgency, deadlines, and safety concerns", "Relationship, channel, and history of similar exchanges"],
    workflow: [
      { name: "Delay irreversible action", instruction: "Preserve the draft without sending while assessing it. If there is no real deadline, create a cooling interval." },
      { name: "Extract the valid need", instruction: "Identify the request, boundary, correction, hurt, or decision beneath the escalation." },
      { name: "Remove heat multipliers", instruction: "Cut insults, threats, mind-reading, absolutes, topic stacking, public shaming, and demands for immediate response." },
      { name: "Choose the right medium", instruction: "Decide whether a short text, email, scheduled conversation, third-party process, or no contact best fits the stakes." },
      { name: "Draft the smallest useful message", instruction: "Use observation, impact, request, and timing. Keep evidence or logistics only when they change the next step." },
      { name: "Run the tomorrow test", instruction: "Check whether the message remains accurate, necessary, and proportionate after the immediate emotion passes." },
    ],
    rules: ["Delay when the main purpose is to discharge emotion.", "Send only time-sensitive logistics when the broader conflict can wait.", "Do not make a conversation request sound like a summons.", "Preserve a clear boundary even while softening escalation."],
    boundaries: ["Do not optimize threats, harassment, coercion, retaliation, or public humiliation.", "For danger, abuse, stalking, or extortion, prioritize safety planning and appropriate local help.", "Do not encourage contact that violates a no-contact request or formal order."],
    output: ["Send/delay/talk decision", "Underlying need", "Removed escalation risks", "Revised message", "Timing and follow-up plan"],
  },
  "household-responsibility-agreement": {
    objective: "Replace recurring chore negotiation with explicit, fair ownership of visible and invisible household work.",
    intake: ["Household members, ages, schedules, and access needs", "Recurring tasks and current ownership", "Planning, noticing, purchasing, and follow-up work", "Conflict points and differing standards", "Capacity changes, paid help, and desired review period"],
    workflow: [
      { name: "Inventory complete responsibilities", instruction: "List each outcome from noticing through planning, supplies, execution, and follow-up. Do not count only the visible final action." },
      { name: "Define minimum standards", instruction: "Describe observable done conditions and frequency. Avoid assuming one person's unstated standard is universal." },
      { name: "Assign ownership", instruction: "Give one person primary ownership for each outcome while allowing agreed assistance. Ownership includes remembering." },
      { name: "Balance total load", instruction: "Compare time, frequency, cognitive load, unpleasantness, flexibility, and each person's external capacity." },
      { name: "Design handoffs and exceptions", instruction: "Specify how coverage is requested, when it is confirmed, and what happens during illness, travel, or unusually busy periods." },
      { name: "Run a trial", instruction: "Use the agreement for a defined period, then review friction and load without relitigating every completed task." },
    ],
    rules: ["Helping is not ownership unless remembering and follow-up also transfer.", "Fair need not mean identical.", "Do not assign one person as permanent household project manager by default.", "Children's responsibilities must be safe and age appropriate."],
    boundaries: ["Do not use a chore agreement to conceal coercive control, financial abuse, or unsafe conditions.", "Respect disability, illness, care load, and paid-work constraints without making medical judgments.", "Do not prescribe gendered roles or cultural assumptions."],
    output: ["Responsibility inventory", "Ownership and minimum standards", "Load-balance notes", "Handoff and exception rules", "Trial period and review questions"],
  },
  "shared-care-coordinator": {
    objective: "Coordinate non-clinical care work so responsibilities, supplies, questions, and handoffs remain visible.",
    intake: ["Person or animal receiving care and their stated preferences", "Care period, locations, and current schedule", "People involved, availability, and authorized roles", "Non-clinical tasks, supplies, transport, and appointments", "Professional instructions already provided and unresolved questions"],
    workflow: [
      { name: "Center the care recipient", instruction: "Record preferences, consent, routines, dignity, communication needs, and decisions they retain." },
      { name: "Separate coordination from treatment", instruction: "List logistical tasks and preserve professional instructions exactly. Put clinical questions in a separate escalation list." },
      { name: "Build the shared schedule", instruction: "Map visits, meals, transport, school, walks, supplies, and appointments with owners and backup coverage." },
      { name: "Assign complete handoffs", instruction: "Define what the next person must know, what changed, what is due, and where essential items are located." },
      { name: "Track supplies and documents", instruction: "Set reorder points and secure locations for relevant records without exposing unnecessary private information." },
      { name: "Review strain and gaps", instruction: "Check uncovered periods, conflicting instructions, consent concerns, and overloaded caregivers. Escalate questions to the appropriate professional or family decision process." },
    ],
    rules: ["Never change a professional instruction.", "Use one source of truth with dated updates.", "Assign backups for high-consequence handoffs.", "Share the minimum necessary private information."],
    boundaries: ["Do not diagnose, dose, prescribe, restrain, or make medical or veterinary decisions.", "Direct urgent symptoms or immediate safety concerns to the appropriate local emergency or clinical service.", "Do not override the capable care recipient's autonomy or consent."],
    output: ["Care preferences and boundaries", "Schedule with owners and backups", "Supply and document tracker", "Standard handoff brief", "Questions and escalation list"],
  },
  "minimum-viable-workout": {
    objective: "Shorten an intended workout while preserving its most important training effect and a safe stopping rule.",
    intake: ["Original workout or training goal", "Available minutes including setup", "Energy, experience, and recent training", "Equipment and space", "Pain, injury, illness, concerning symptoms, pregnancy, or medical restrictions"],
    workflow: [
      { name: "Screen suitability", instruction: "Stop ordinary adaptation if the user reports injury, pain, illness, concerning symptoms, or a need for medical clearance." },
      { name: "Identify the session intent", instruction: "Name the primary adaptation such as strength practice, aerobic base, technique, or mobility. Preserve only one main intent when time is short." },
      { name: "Protect the essential work", instruction: "Keep the most specific movement or intensity block and remove accessories, redundancy, and low-value setup." },
      { name: "Choose substitutions", instruction: "Match movement pattern and effort to available equipment and skill. Prefer familiar movements under time pressure." },
      { name: "Set conservative volume", instruction: "Specify sets, repetitions or time, rest, and an effort ceiling that leaves technical margin." },
      { name: "Define stop and finish", instruction: "Include a short warm-up, pain-free technique checks, stop conditions, and a simple completion record." },
    ],
    rules: ["Preserve intent before variety.", "Do not compensate for shorter time with reckless intensity.", "Prefer fewer high-quality sets to rushed circuits.", "The user may stop early without turning the session into a failure."],
    boundaries: ["Do not adapt around acute pain, injury rehabilitation, fainting, chest pain, unusual breathlessness, or other concerning symptoms.", "Do not provide medical clearance or pregnancy-specific programming.", "Encourage qualified coaching for unfamiliar high-risk lifts or equipment."],
    output: ["Session intent", "Time-boxed warm-up", "Essential work and substitutions", "Effort and rest guidance", "Stop conditions and completion marker"],
  },
  "return-to-exercise": {
    objective: "Build a conservative restart after a lapse that restores consistency before volume or intensity.",
    intake: ["Previous activity and length of lapse", "Current daily activity and confidence", "Available days, time, equipment, and preferred movement", "Reason the routine stopped", "Pain, injury, illness, concerning symptoms, or required medical clearance"],
    workflow: [
      { name: "Confirm a routine restart", instruction: "Separate ordinary detraining or schedule disruption from injury rehabilitation, illness recovery, or a medical question." },
      { name: "Set a deliberately easy baseline", instruction: "Choose activity the user can complete with substantial reserve. Use current capacity, not former personal bests." },
      { name: "Define the minimum week", instruction: "Schedule a small number of sessions with flexible windows and a reduced version for difficult days." },
      { name: "Control progression", instruction: "Change only one of frequency, duration, volume, or intensity at a time after the current level feels repeatable." },
      { name: "Plan for interruption", instruction: "Create a one-missed-session rule and a restart action that prevents an all-or-nothing response." },
      { name: "Review response", instruction: "Track completion, effort, soreness, enjoyment, and concerning symptoms. Keep, reduce, or progress using explicit criteria." },
    ],
    rules: ["Start below what motivation suggests.", "Consistency is the first progression target.", "Do not recreate the user's former workload in week one.", "Prefer activities the user is willing and able to repeat."],
    boundaries: ["Do not provide injury rehabilitation, post-operative recovery, or medical clearance.", "Stop and seek appropriate care for chest pain, fainting, severe breathlessness, acute pain, or other concerning symptoms.", "Respect clinician-provided restrictions without modification."],
    output: ["Suitability and assumptions", "Two-week conservative schedule", "Reduced-session option", "Progression criteria", "Stop conditions and review"],
  },
  "sleep-wind-down-reset": {
    objective: "Design a small evening experiment that reduces friction between the user's real life and intended bedtime.",
    intake: ["Typical sleep and wake times across the week", "Evening activities, responsibilities, and variable constraints", "Where the routine breaks", "Light, noise, temperature, device, and caffeine context", "Persistent symptoms, shift work, or diagnosed sleep conditions"],
    workflow: [
      { name: "Locate the friction", instruction: "Identify the earliest point the evening drifts, such as unfinished work, entertainment loops, chores, worry capture, or poor environment." },
      { name: "Choose one anchor", instruction: "Use a stable wake time, shutdown cue, device parking time, or first wind-down action that can survive variable evenings." },
      { name: "Reduce activation", instruction: "Replace stimulating, bright, effortful, or open-ended activities with a brief sequence the user actually likes." },
      { name: "Prepare the environment", instruction: "Move needed items, lower avoidable light or noise, and remove one recurring source of friction before the routine begins." },
      { name: "Create late-night fallback", instruction: "Define a shorter version for evenings that run late so the routine does not become all-or-nothing." },
      { name: "Run a seven-night test", instruction: "Measure adherence and ease rather than claiming treatment. Change one element after reviewing the pattern." },
    ],
    rules: ["Make the first cue easier than relying on willpower at bedtime.", "Do not prescribe a perfect routine that exceeds the user's evening capacity.", "Keep clocks and metrics from increasing anxiety.", "Treat the experiment as information, not a streak."],
    boundaries: ["Do not diagnose or treat insomnia, sleep apnea, persistent fatigue, parasomnias, or mental-health conditions.", "Recommend clinical evaluation for persistent sleep problems, breathing pauses, dangerous sleepiness, or concerning symptoms.", "Do not recommend changing medication or substance use without qualified guidance."],
    output: ["Friction diagnosis", "Primary anchor", "Wind-down sequence", "Late-night fallback", "Seven-night review measure"],
  },
  "habit-recovery": {
    objective: "Understand why a routine broke and create a smaller restart that remains meaningful under real constraints.",
    intake: ["Habit and the outcome it was meant to support", "What happened before the break", "Previous cue, action, environment, and reward", "Current capacity and recurring obstacles", "Minimum version that would still matter"],
    workflow: [
      { name: "Remove moral judgment", instruction: "Describe the break as data about design, context, and capacity. Do not use shame as a motivational device." },
      { name: "Diagnose the failure mode", instruction: "Check cue loss, excess scope, unclear action, environment friction, competing rewards, schedule change, or a habit that no longer serves the goal." },
      { name: "Choose keep, redesign, or retire", instruction: "Confirm the habit still matters. Do not restart a routine only to preserve identity or a streak." },
      { name: "Shrink the action", instruction: "Create a version that begins easily and still represents the target behavior. Keep expansion optional." },
      { name: "Attach a reliable cue", instruction: "Use an event or environment the user already encounters and prepare the needed materials in advance." },
      { name: "Install recovery logic", instruction: "Define what happens after a miss, when to reduce scope, and when to review after a short trial." },
    ],
    rules: ["Never require making up missed repetitions.", "A minimum version must be specific and observable.", "Use environment changes before adding reminders.", "Retiring a useless habit can be a successful outcome."],
    boundaries: ["Do not treat addiction, eating disorders, compulsions, self-harm, or clinical symptoms as ordinary habit design.", "Do not recommend medication changes or punitive consequences.", "Preserve the user's autonomy and reasons for changing."],
    output: ["Failure-mode diagnosis", "Keep/redesign/retire decision", "Minimum restart", "Cue and friction changes", "Miss rule and review date"],
  },
  "desk-day-movement-plan": {
    objective: "Fit brief movement, posture variation, and visual breaks into the user's actual desk schedule without presenting them as treatment.",
    intake: ["Work hours, location, and meeting schedule", "Control over breaks and camera use", "Current movement, commute, and workspace", "Preferred quiet or standing options", "Pain, numbness, weakness, dizziness, vision concerns, or medical restrictions"],
    workflow: [
      { name: "Map natural transitions", instruction: "Find meeting ends, file loads, calls, meals, restroom trips, and task changes where movement can occur without another alarm." },
      { name: "Choose varied actions", instruction: "Alternate standing, walking, reaching, gentle range changes, and looking at different distances. Avoid claiming one posture is perfect." },
      { name: "Size each break", instruction: "Use actions from twenty seconds to a few minutes that fit the actual transition. Keep longer activity separate." },
      { name: "Prepare quiet alternatives", instruction: "Provide camera-on, shared-office, travel, and high-focus variants that do not require floor space or equipment." },
      { name: "Change the environment", instruction: "Place water, headphones, bins, or frequently used items to encourage safe variation rather than inconvenience." },
      { name: "Review feasibility", instruction: "Track whether cues were noticed and whether movement felt comfortable. Adjust placement before increasing frequency." },
    ],
    rules: ["Variation matters more than enforcing one ideal posture.", "Do not interrupt safety-critical or high-stakes meetings.", "Avoid painful or forced movements.", "Use the fewest reminders that reliably work."],
    boundaries: ["Do not diagnose or treat pain, repetitive strain, vision disorders, or neurological symptoms.", "Recommend qualified care for persistent pain, weakness, numbness, severe headaches, dizziness, or concerning visual symptoms.", "Respect workplace safety and clinician restrictions."],
    output: ["Transition map", "Meeting-aware movement cues", "Quiet and busy-day alternatives", "Environment adjustments", "One-week feasibility review"],
  },
  "decision-journal": {
    objective: "Capture the quality of a decision at the time it is made so later outcomes do not rewrite the original reasoning.",
    intake: ["Decision, deadline, and decision owner", "Objectives, constraints, and affected people", "Options including delay or no action", "Evidence, assumptions, and important unknowns", "Reversibility, downside, confidence, and review horizon"],
    workflow: [
      { name: "Frame the decision", instruction: "Write one decision statement with scope, owner, and deadline. Separate it from related future decisions." },
      { name: "State objectives and options", instruction: "List the outcomes that matter and preserve genuine alternatives, including waiting when available." },
      { name: "Record the current model", instruction: "Document evidence, key assumptions, probability estimates, and what the user expects to happen." },
      { name: "Run the premortem", instruction: "Imagine the chosen path failed and identify plausible causes, leading indicators, and preventions." },
      { name: "Match process to reversibility", instruction: "Use faster tests for reversible choices and more evidence or safeguards for irreversible, high-downside choices." },
      { name: "Set the review", instruction: "Choose a date or signal, define what information will be available, and separate process quality from outcome quality." },
    ],
    rules: ["Timestamp beliefs and confidence.", "Do not hide uncertainty inside vague language.", "A good outcome does not prove a good process.", "Record what would change the decision."],
    boundaries: ["Do not make medical, legal, financial, or safety-critical decisions for the user.", "Surface affected stakeholders and consent where relevant.", "Recommend qualified advice when the decision requires regulated expertise."],
    output: ["Decision frame", "Objectives and alternatives", "Evidence, assumptions, and confidence", "Premortem and safeguards", "Choice, review trigger, and evaluation criteria"],
  },
  "personal-project-rescue": {
    objective: "Recover enough context from a stalled personal project to make one meaningful milestone finishable.",
    intake: ["Original project and why it mattered", "Existing files, notes, materials, and last known state", "How long it has been stalled", "Current time, energy, budget, and interest", "Known blockers, obligations, and desired definition of done"],
    workflow: [
      { name: "Reconstruct the state", instruction: "Inventory what exists, what works, what is undecided, and the last completed action. Do not restart from the original vision by default." },
      { name: "Verify continued value", instruction: "Ask whether finishing, reducing, transferring, archiving, or abandoning best serves the user now." },
      { name: "Locate the blockage", instruction: "Distinguish missing information, excess scope, difficult setup, fear of evaluation, low value, dependency, or unclear next action." },
      { name: "Cut to a finishable milestone", instruction: "Define one observable result that delivers value or learning without completing the whole project." },
      { name: "Prepare re-entry", instruction: "Gather materials, write a current-state note, and create a first work block that begins with a concrete action." },
      { name: "Protect the next handoff", instruction: "End each session with a short status, next action, and materials ready so context does not decay again." },
    ],
    rules: ["Preserve useful existing work before redesigning.", "Abandoning deliberately is allowed.", "Reduce scope before extending the deadline.", "The first milestone must be finishable with current resources."],
    boundaries: ["Do not turn personal projects into compulsory productivity.", "Do not recommend spending or commitments beyond the user's limits.", "Respect intellectual property, privacy, and obligations to collaborators."],
    output: ["Recovered project state", "Continue/change/archive decision", "Blockage diagnosis", "Reduced milestone", "Re-entry block and end-of-session handoff"],
  },
  "learn-by-doing": {
    objective: "Turn a learning goal into active practice with feedback and retrieval rather than a passive content list.",
    intake: ["Skill or concept and desired real-world capability", "Current level and prior attempts", "Time available now and over the next week", "Tools, examples, and constraints", "How success can be observed or tested"],
    workflow: [
      { name: "Define the performance", instruction: "Translate 'understand' into something the learner can explain, choose, create, solve, or demonstrate." },
      { name: "Give the smallest model", instruction: "Explain only the concepts needed for the first attempt, using one clear example and explicit success criteria." },
      { name: "Work one example", instruction: "Demonstrate the process while naming decisions and common errors. Do not hide essential reasoning." },
      { name: "Guide an attempt", instruction: "Give a nearby task with prompts or checkpoints. Let the learner produce the work before correcting it." },
      { name: "Require an independent attempt", instruction: "Remove scaffolding for a fresh but comparable task, then give specific feedback against the criteria." },
      { name: "Schedule retrieval and transfer", instruction: "Create short later prompts that recall the idea and apply it in a different context." },
    ],
    rules: ["Ask for an attempt before revealing the full solution when safe.", "Feedback must name the gap and next correction.", "Increase difficulty by one dimension at a time.", "Use examples relevant to the learner's actual goal."],
    boundaries: ["Do not facilitate cheating, impersonation, unsafe practice, or evasion of assessment rules.", "Do not present professional certification or competency without valid assessment.", "Adapt for accessibility and prior knowledge without lowering the stated success criterion invisibly."],
    output: ["Observable learning target", "Minimal explanation", "Worked example", "Guided and independent attempts", "Feedback and retrieval schedule"],
  },
  "packing-by-scenario": {
    objective: "Pack for the actual itinerary and consequences of failure while staying within luggage constraints.",
    intake: ["Destinations, dates, itinerary, and current weather source", "Activities, formality, local norms, and access needs", "Luggage dimensions, weight, and carrier rules", "Laundry, accommodation, and shopping access", "Documents, medications, devices, and hard-to-replace essentials"],
    workflow: [
      { name: "Map scenarios", instruction: "List transit, sleep, routine days, weather exposure, work, exercise, events, and return travel. Remove imagined scenarios with no itinerary support." },
      { name: "Set critical items", instruction: "Identify documents, prescribed medication, accessibility items, keys, payment access, and devices whose absence has serious consequences." },
      { name: "Build a clothing system", instruction: "Choose repeatable layers and compatible items by scenario, weather, laundry, and local norms rather than by day alone." },
      { name: "Allocate luggage", instruction: "Place critical and first-day items in the personally carried bag. Check liquid, battery, sharp, and restricted-item rules from current authoritative sources." },
      { name: "Cut and verify", instruction: "Remove duplicates with low consequence, weigh or measure the bag, and preserve a small capacity buffer." },
      { name: "Run the departure sweep", instruction: "Check documents, medication, chargers, keys, wallet, itinerary, home shutdown, and the wear-in-transit plan." },
    ],
    rules: ["Consequences of forgetting outrank convenience.", "Do not pack for every remote possibility.", "Verify current weather and operator rules; do not rely on memory.", "Keep critical items accessible and distributed when practical."],
    boundaries: ["Do not advise carrying prohibited, undeclared, or improperly stored items.", "Do not alter prescribed medication or documentation requirements.", "Ask for destination and nationality context before discussing border or cultural requirements."],
    output: ["Scenario map", "Critical carry-on list", "Clothing and gear system", "Cut list and constraint check", "Final departure sweep"],
  },
  "travel-day-contingency": {
    objective: "Audit a travel day for likely failure points and create a compact offline recovery brief.",
    intake: ["Full dated itinerary with local time zones", "Operators, booking references, airports or stations, and terminals", "Passport, visa, entry, and carrier requirements already verified", "Baggage, medication, mobility, dependents, and connectivity", "Payment methods, insurance, accommodation, and destination transport"],
    workflow: [
      { name: "Normalize the timeline", instruction: "Convert each segment to local date and time, include check-in or boarding cutoffs, and mark independent tickets or terminal changes." },
      { name: "Audit transfer buffers", instruction: "Account for immigration, security, baggage reclaim, recheck, walking, transport variability, and the last available onward service." },
      { name: "Protect critical access", instruction: "Keep verified documents, medication, keys, payment, contacts, and one change of essentials personally accessible." },
      { name: "Prepare offline continuity", instruction: "Save itinerary, addresses, tickets where permitted, maps, policy details, and verified contact routes without relying on one device." },
      { name: "Plan failure branches", instruction: "Write the first three actions for delay, cancellation, missed connection, lost bag, dead phone, and closed onward transport." },
      { name: "Set live verification points", instruction: "Identify what must be rechecked with authoritative operator or government sources before departure and during travel." },
    ],
    rules: ["Use local dates and time zones explicitly.", "Do not assume protected connections across separate bookings.", "Independent verified contacts outrank links in unsolicited disruption messages.", "Prioritize safety, documents, medication, shelter, and communication before reimbursement administration."],
    boundaries: ["Do not guarantee entry, boarding, compensation, or connection feasibility.", "Use current authoritative government and operator sources for border, visa, security, and timetable claims.", "Do not recommend unsafe rushing, bypassing controls, or separating dependents from required support."],
    output: ["Normalized travel timeline", "Buffer and risk audit", "Critical-access checklist", "Failure-branch actions", "Compact offline fallback brief"],
  },
};
