import Link from "next/link";

const stages = [
  ["01", "Package integrity", "Frontmatter, agent metadata, referenced files, suite shape, and whole-package hash integrity."],
  ["02", "Scenario map", "Four normal cases, two clarification cases, two negative routes, one difficult edge, and one adversarial safety case."],
  ["03", "Instruction review", "GPT-5 (Codex) reads the complete package and checks whether its written procedure addresses each scenario."],
  ["04", "Coverage evidence", "Each expected route, required behavior, and prohibited behavior receives a written instruction-level justification."],
  ["05", "Hash-bound record", "The review remains current only while the package and suite hashes match the exact files people inspect."],
];

export default function MethodologyPage() {
  return <div className="method-page">
    <header className="method-hero"><p className="eyebrow">Methodology · version 3</p><h1>Show the evidence level—not a prettier number.</h1><p>The current review checks whether each written package covers its scenarios, routes, and safety boundaries. It does not execute or compare agent outputs, so we do not publish a numeric quality score.</p></header>
    <section className="selection-gates"><div><p className="eyebrow">Before authoring</p><h2>Four catalog gates</h2></div><ol><li><strong>Recurring need</strong><span>The situation repeats or carries meaningful consequences.</span></li><li><strong>Procedural advantage</strong><span>A reusable workflow beats a clever one-off prompt.</span></li><li><strong>Observable output</strong><span>The result can be inspected: a brief, plan, schedule, decision, agreement, or checklist.</span></li><li><strong>Safe boundary</strong><span>The agent can help without pretending to be an emergency authority or regulated professional.</span></li></ol></section>
    <section className="evaluation-stages"><div className="section-heading"><div><p className="eyebrow">The review pipeline</p><h2>Five stages. One exact package.</h2></div><p>Editing SKILL.md or any supporting file changes the SHA-256 hash and immediately makes the older review stale.</p></div><div>{stages.map(([number, title, description]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="thresholds"><div><p className="eyebrow">Current evidence</p><h2>Instruction coverage, clearly labeled.</h2><p>“Instructions reviewed” means Codex found written coverage for the suite. It does not mean the skill has beaten a baseline or succeeded in real-world use.</p></div><dl><div><dt>Scenario records</dt><dd>10/10</dd></div><div><dt>Critical boundaries</dt><dd>100%</dd></div><div><dt>Written routing coverage</dt><dd>≥ 90%</dd></div><div><dt>Package hash</dt><dd>Current</dd></div><div><dt>Suite hash</dt><dd>Current</dd></div><div><dt>Execution comparison</dt><dd>Not run</dd></div></dl></section>
    <section className="selection-gates"><div><p className="eyebrow">Next evidence level</p><h2>What a numeric grade requires</h2></div><ol><li><strong>Saved outputs</strong><span>Preserve a baseline and skill-enabled response for every scenario.</span></li><li><strong>Blind comparison</strong><span>Randomize output order before judging which response better meets the rubric.</span></li><li><strong>Reproducible record</strong><span>Publish prompts, outputs, model identity, settings, hashes, and review notes.</span></li><li><strong>Calibrated scoring</strong><span>Show distributions and uncertainty instead of manufacturing identical precision.</span></li></ol></section>
    <section className="evidence-section"><p className="eyebrow">Why everyday work</p><h2>The catalog follows actual consumer needs.</h2><div className="evidence-grid"><a href="https://openai.com/index/how-people-are-using-chatgpt/" rel="noreferrer"><strong>Consumer AI use</strong><span>Practical guidance, information, and writing dominate consumer use; most is non-work related. ↗</span></a><a href="https://www.bls.gov/news.release/archives/atus_06252026.htm" rel="noreferrer"><strong>Daily household work</strong><span>Food preparation, cleaning, and shopping remain recurring parts of adult life. ↗</span></a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11761833/" rel="noreferrer"><strong>Cognitive household labor</strong><span>Household work includes anticipating, planning, scheduling, reminding, and monitoring. ↗</span></a><a href="https://consumer.ftc.gov/" rel="noreferrer"><strong>Consumer protection</strong><span>Official guidance repeatedly addresses scams, purchases, refunds, and recurring consumer problems. ↗</span></a></div></section>
    <section className="method-cta"><h2>Inspect the packages yourself.</h2><p>Every skill page exposes every included file, the exact package hash, and its honest evaluation state.</p><Link className="button primary" href="/#library">Browse the library</Link></section>
  </div>;
}
