import Link from "next/link";

const stages = [
  ["01", "Structure", "Frontmatter, required sections, length, prohibited content, and hash integrity."],
  ["02", "Routing", "Four normal cases, two clarification cases, two negative routes, one difficult edge, and one adversarial safety case."],
  ["03", "Comparison", "The same scenario runs without the skill and with the exact published SKILL.md."],
  ["04", "Blind judgment", "Randomized outputs are scored for usefulness, correctness, fit, autonomy, and safety."],
  ["05", "Human review", "A reviewer inspects failures, boundary behavior, and whether the output is genuinely usable."],
];

export default function MethodologyPage() {
  return <div className="method-page">
    <header className="method-hero"><p className="eyebrow">Methodology · version 1</p><h1>A skill is only useful if it changes the work.</h1><p>We test for more than polished prose. A passing skill must route correctly, improve the result against a no-skill baseline, respect its boundaries, and remain bound to the exact file people install.</p></header>
    <section className="selection-gates"><div><p className="eyebrow">Before authoring</p><h2>Four catalog gates</h2></div><ol><li><strong>Recurring need</strong><span>The situation repeats or carries meaningful consequences.</span></li><li><strong>Procedural advantage</strong><span>A reusable workflow beats a clever one-off prompt.</span></li><li><strong>Observable output</strong><span>The result can be inspected: a brief, plan, schedule, decision, agreement, or checklist.</span></li><li><strong>Safe boundary</strong><span>The agent can help without pretending to be an emergency authority or regulated professional.</span></li></ol></section>
    <section className="evaluation-stages"><div className="section-heading"><div><p className="eyebrow">The evaluation pipeline</p><h2>Five stages. One exact file.</h2></div><p>Editing SKILL.md changes its SHA-256 hash and immediately invalidates any older passing report.</p></div><div>{stages.map(([number, title, description]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="thresholds"><div><p className="eyebrow">Launch threshold</p><h2>Passing is intentionally difficult.</h2><p>A report can be structurally valid without being marked tested. The public status appears only after the full comparison and human review pass.</p></div><dl><div><dt>Critical safety cases</dt><dd>100%</dd></div><div><dt>Routing accuracy</dt><dd>≥ 90%</dd></div><div><dt>Weighted quality</dt><dd>≥ 85/100</dd></div><div><dt>Skill-enabled wins</dt><dd>≥ 70%</dd></div><div><dt>Skill-enabled losses</dt><dd>≤ 10%</dd></div><div><dt>Rubric floor</dt><dd>3/5</dd></div></dl></section>
    <section className="evidence-section"><p className="eyebrow">Why everyday work</p><h2>The catalog follows actual consumer needs.</h2><div className="evidence-grid"><a href="https://openai.com/index/how-people-are-using-chatgpt/" rel="noreferrer"><strong>Consumer AI use</strong><span>Practical guidance, information, and writing dominate consumer use; most is non-work related. ↗</span></a><a href="https://www.bls.gov/news.release/archives/atus_06252026.htm" rel="noreferrer"><strong>Daily household work</strong><span>Food preparation, cleaning, and shopping remain recurring parts of adult life. ↗</span></a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11761833/" rel="noreferrer"><strong>Cognitive household labor</strong><span>Household work includes anticipating, planning, scheduling, reminding, and monitoring. ↗</span></a><a href="https://consumer.ftc.gov/" rel="noreferrer"><strong>Consumer protection</strong><span>Official guidance repeatedly addresses scams, purchases, refunds, and recurring consumer problems. ↗</span></a></div></section>
    <section className="method-cta"><h2>Inspect the procedures yourself.</h2><p>Every skill page exposes the complete Markdown, exact hash, and evaluation state.</p><Link className="button primary" href="/#library">Browse the library</Link></section>
  </div>;
}
